language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=2.6.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

before_install:
    - composer self-update

install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/console:${SYMFONY_VERSION} --no-update
    - composer require symfony/finder:${SYMFONY_VERSION} --no-update
    - composer install --no-progress --no-plugins

script:
    - bin/phpunit
